const locationNames =[
    {id: 1, name: "Earth (C-137)"},
    {id: 2, name: "Abadango"},
    {id: 3, name: "Citadel of Ricks"},
    {id: 4, name: "Worldender's lair"},
    {id: 5, name: "Anatomy Park"},
    {id: 6, name: "Interdimensional Cable"},
    {id: 7, name: "Immortality Field Resort"},
    {id: 8, name: "Post-Apocalyptic Earth"},
    {id: 9, name: "Purge Planet"},
    {id: 10, name: "Venzenulon 7"},
    {id: 11, name: "Bepis 9"},
    {id: 12, name: "Cronenberg Earth"},
    {id: 13, name: "Nuptia 4"},
    {id: 14, name: "Giant's Town"},
    {id: 15, name: "Bird World"},
    {id: 16, name: "St. Gloopy Noops Hospital"},
    {id: 17, name: "Earth (5-126)"},
    {id: 18, name: "Mr. Goldenfold's dream"},
    {id: 19, name: "Gromflom Prime"},
    {id: 20, name: "Earth (Replacement Dimension)"},
    {id: 21, name: "Testicle Monster Dimension"},
    {id: 22, name: "Signus 5 Expanse"},
    {id: 23, name: "Earth (C-500A)"},
    {id: 24, name: "Rick's Battery Microverse"},
    {id: 25, name: "The Menagerie"},
    {id: 26, name: "Earth (K-83)"},
    {id: 27, name: "Hideout Planet"},
    {id: 28, name: "Unity's Planet"},
    {id: 29, name: "Dorian 5"},
    {id: 30, name: "Earth (Unknown dimension)"},
    {id: 31, name: "Earth (J19ζ7)"},
    {id: 32, name: "Roy: A Life Well Lived"},
    {id: 33, name: "Eric Stoltz Mask Earth"},
    {id: 34, name: "Earth (Evil Rick's Target Dimension)"},
    {id: 35, name: "Planet Squanch"},
    {id: 36, name: "Glaagablaaga"},
    {id: 37, name: "Resort Planet"},
    {id: 38, name: "Interdimensional Customs"},
    {id: 39, name: "Galactic Federation Prison"},
    {id: 40, name: "Gazorpazorp"},
    {id: 41, name: "Hamster in Butt World"},
    {id: 42, name: "Earth (Giant Telepathic Spiders Dimension)"},
    {id: 43, name: "Alphabetrium"},
    {id: 44, name: "Jerryboree"},
    {id: 45, name: "Krootabulon"},
    {id: 46, name: "Zigerion's Base"},
    {id: 47, name: "Pluto"},
    {id: 48, name: "Fantasy World"},
    {id: 49, name: "Zeep Xanflorp's Miniverse"},
    {id: 50, name: "Kyle's Teenyverse"},
    {id: 51, name: "Larva Alien's Planet"},
    {id: 52, name: "Earth (K-22)"},
    {id: 53, name: "Mr. Meeseeks Box"},
    {id: 54, name: "Vindicator's Base"},
    {id: 55, name: "Pawn Shop Planet"},
    {id: 56, name: "Mega Gargantuan Kingdom"},
    {id: 57, name: "Gear World"},
    {id: 58, name: "Earth (D-99)"},
    {id: 59, name: "Earth (D716)"},
    {id: 60, name: "Earth (D716-B)"},
    {id: 61, name: "Earth (D716-C)"},
    {id: 62, name: "Earth (J-22)"},
    {id: 63, name: "Froopyland"},
    {id: 64, name: "Detoxifier"},
    {id: 65, name: "Trunk World"},
    {id: 66, name: "Plopstar"},
    {id: 67, name: "Blips and Chitz"},
    {id: 68, name: "Girvonesk"},
    {id: 69, name: "Earth (C-35)"},
    {id: 70, name: "Snuffles' Dream"},
    {id: 71, name: "Earth (Pizza Dimension)"},
    {id: 72, name: "Earth (Phone Dimension)"},
    {id: 73, name: "Greasy Grandma World"},
    {id: 74, name: "Earth (Chair Dimension)"},
    {id: 75, name: "Árboles Mentirosos"},
    {id: 76, name: "Alien Day Spa"},
    {id: 77, name: "Earth (Fascist Dimension)"},
    {id: 78, name: "Snake Planet"},
    {id: 79, name: "Forbodulon Prime"},
    {id: 80, name: "Earth (Fascist Shrimp Dimension)"},
    {id: 81, name: "Earth (Fascist Teddy Bear Dimension)"},
    {id: 82, name: "Earth (Wasp Dimension)"},
    {id: 83, name: "Monogatron Mothership"},
    {id: 84, name: "Gorgon Quadrant"},
    {id: 85, name: "Midland Quasar"},
    {id: 86, name: "Mount Space Everest"},
    {id: 87, name: "Globaflyn"},
    {id: 88, name: "Heist-Con"},
    {id: 89, name: "Heistotron Base"},
    {id: 90, name: "Mount Olympus"},
    {id: 91, name: "Plitzville Montana"},
    {id: 92, name: "Earth (Tusk Dimension)"},
    {id: 93, name: "Gramuflack"},
    {id: 94, name: "Draygon"},
    {id: 95, name: "New Improved Galactic Federation Quarters"},
    {id: 96, name: "Story Train"},
    {id: 97, name: "Non-Diegetic Alternative Reality"},
    {id: 98, name: "Tickets Please Guy Nightmare"},
    {id: 99, name: "Morty’s Story"},
    {id: 100, name: "Ricks’s Story"},
    {id: 101, name: "Glorzo Asteroid"},
    {id: 102, name: "Alien Acid Plant"},
    {id: 103, name: "Merged Universe"},
    {id: 104, name: "Near-Duplicate Reality"},
    {id: 105, name: "NX-5 Planet Remover"},
    {id: 106, name: "Gaia"},
    {id: 107, name: "Defiance's Ship"},
    {id: 108, name: "Defiance's Base"},
    {id: 109, name: "The Ocean"},
    {id: 110, name: "Narnia Dimension"},
    {id: 111, name: "Elemental Rings"},
    {id: 112, name: "Morglutz"},
    {id: 113, name: "Ferkus 9"},
    {id: 114, name: "Morty"},
    {id: 115, name: "Space"},
    {id: 116, name: "Hell"},
    {id: 117, name: "Z. Q. P. D."},
    {id: 118, name: "Space Tahoe"},
    {id: 119, name: "France"},
    {id: 120, name: "Birdperson's Consciousness"},
    {id: 121, name: "Rick's Consciousness"},
    {id: 122, name: "Avian Planet"},
    {id: 123, name: "Normal Size Bug Dimension"},
    {id: 124, name: "Slartivart"},
    {id: 125, name: "Rick and Two Crows Planet"},
    {id: 126, name: "Rick's Memories"}
]

export {
    locationNames,
}